### ISSUE TITLE
Browser keyboard shortcuts aren't working

### ISSUE THREAD

**Issue by dan-tripp-siteimprove** [w3c/wai-website#1028]
### Resource URL

https://www.w3.org/WAI/test-evaluate/preliminary/

### Description

When I'm on the "Easy Checks" page, my browser keyboard shortcuts aren't working: shortcuts such as alt+d (go to address bar), ctrl+f (find on page), and ctrl+r (reload page).

I saw this behaviour in Chrome, Firefox, and Edge.

I don't know if this is related, but I see this error message in the Chrome devtools console every time I press alt+d:

```
ableplayer.min.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'prefAltKey')
    at AblePlayer.getAvailablePreferences (ableplayer.min.js:3:35392)
    at AblePlayer.updateCookie (ableplayer.min.js:3:34941)
    at AblePlayer.handleDescriptionToggle (ableplayer.min.js:3:136313)
    at AblePlayer.onPlayerKeyPress (ableplayer.min.js:3:178479)
    at ableplayer.min.js:3:407
    at dispatch (jquery.min.js:3:10316)
    at q.handle (jquery.min.js:3:8343)
```

and this error message every time I press ctrl+f:

```
ableplayer.min.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at AblePlayer.handleFastForward (ableplayer.min.js:3:132650)
    at AblePlayer.onPlayerKeyPress (ableplayer.min.js:3:178566)
    at ableplayer.min.js:3:407
    at dispatch (jquery.min.js:3:10316)
    at q.handle (jquery.min.js:3:8343)
```

I saw some other error messages in Firefox - not the same messages as Chrome, but also mentioning "ableplayer.min.js".

My keyboard shortcuts work normally on [this ableplayer demo page](https://ableplayer.github.io/ableplayer/demos/video3.html).

### Resource Shortname

wai-easy-checks

**Comment by dan-tripp-siteimprove** [comment]
If anyone is looking for a workaround: I made this bookmarklet (attached) which makes ctrl+f work again for me.  Also, here is the bookmarklet in tampermonkey form, if you're into that:

```// ==UserScript==
// @name         WAI easy checks
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  .
// @author       Dan Tripp (dtr@siteimprove.com) 
// @match       https://www.w3.org/WAI/test-evaluate/preliminary/
// @run-at       document-idle
// ==/UserScript==
var tamperMonkeyScriptVars_57278cda_05dc_4ae5_84df_40b284053793;
(async function (scriptVars) {

	async function runMain() {

        if(window.location.href === "https://www.w3.org/WAI/test-evaluate/preliminary/") {
            // see https://github.com/w3c/wai-website/issues/1028 
            /* seems like this won't work if the "video" disclosure is open.  which happens both if you do it explicitly and if you go to that fragment URL. */ 

            function rescueKeyDown(e) {
                if (e.ctrlKey || e.altKey || (e.key.toLowerCase() === 'f3')) {
                    e.stopPropagation();
                }
            }
            for (let type of ["keydown"]) {
                window.addEventListener(type, rescueKeyDown, true);
            }
            console.log("(tampermonkey) fixed keyboard shortcuts for WAI page.");
        }

	}

	function callFuncOnDocumentReady(func_, runIfWeAreInAnIframe_) {
		if(!runIfWeAreInAnIframe_) {
			let areWeInAnIframe = window.self !== window.top;
			if(areWeInAnIframe) return;
		}
		if(document.readyState == "complete") {
			/* This will probably happen if we're running as a bookmarklet.  i.e. it's now 
			well after page load is finished. */
			func_();
		} else {
			/* This will happen if we're running as a tampermonkey script.  
			i.e. it's now well before page load is finished. */
			document.addEventListener("readystatechange", (event__) => {
				if(document.readyState === "complete") {
					func_();
				}
			});
		}
	}

	callFuncOnDocumentReady(runMain, false);

})(tamperMonkeyScriptVars_57278cda_05dc_4ae5_84df_40b284053793 || (tamperMonkeyScriptVars_57278cda_05dc_4ae5_84df_40b284053793 = {}));
```

[wai-easy-checks-bookmarklet-minified.js.txt](https://github.com/user-attachments/files/19918626/wai-easy-checks-bookmarklet-minified.js.txt)
